apiVersion: v1
kind: Service
metadata:
  name: flag-service
  namespace: techchallenge
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: flag-service