apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: techchallenge
type: Opaque
data:
  # Base64
  MASTER_KEY: c3VwZXJzZWNyZXRrZXk=
  DB_AUTH_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3JlczEyM0BhdXRoLXNlcnZpY2UtZGIuY2hhdmVzLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL2F1dGhfZGI=
  DB_FLAG_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3JlczEyM0BmbGFnLXNlcnZpY2UtZGIuY2hhdmVzLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL2ZsYWdfZGI=
  DB_TARGETING_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3JlczEyM0B0YXJnZXRpbmctc2VydmljZS1kYi5jaGF2ZXMudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvdGFyZ2V0aW5nX2Ri