apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: techchallenge
type: Opaque
stringData:
  MASTER_KEY: "auth_service_login"
  DB_AUTH_URL: "postgres://postgres:postgres123@auth-service-db.cjc2zfgxdo1d.us-east-1.rds.amazonaws.com:5432/auth_db?sslmode=require"
  DB_FLAG_URL: "postgres://postgres:postgres123@flag-service-db.cjc2zfgxdo1d.us-east-1.rds.amazonaws.com:5432/flag_db?sslmode=require"
  DB_TARGETING_URL: "postgres://postgres:postgres123@targeting-service-db.cjc2zfgxdo1d.us-east-1.rds.amazonaws.com:5432/targeting_db?sslmode=require"