apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-config
  namespace: techchallenge
data:
  PORT: "8004"
  REDIS_HOST: "evaluation-redis.XXXXX.use1.cache.amazonaws.com"
  REDIS_PORT: "6379"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/123456789012/techchallenge2-queue"
  AWS_REGION: "us-east-1"