apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: techchallenge
  labels:
    app: evaluation-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
        - name: evaluation-service
          image: 076974753162.dkr.ecr.us-east-1.amazonaws.com/evaluation-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: evaluation-service-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: AUTH_SERVICE_URL
              value: http://auth-service:8080
            - name: FLAG_SERVICE_URL
              value: http://flag-service:8080
            - name: TARGETING_SERVICE_URL
              value: http://targeting-service:8080
            - name: REDIS_URL
              value: "redis://evaluation-redis.tlcbzq.0001.use1.cache.amazonaws.com:6379"